"""Add orden column to TipoAplicativo

Revision ID: 0772d5b7e311
Revises: 351e465ba2b0
Create Date: 2025-11-21 20:30:05.455677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0772d5b7e311'
down_revision = '351e465ba2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Comentamos esta sección autogenerada que causa el error.
    # with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idAlumno'))

    with op.batch_alter_table('tipo_aplicativo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orden', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipo_aplicativo', schema=None) as batch_op:
        batch_op.drop_column('orden')

    # Comentamos también la parte correspondiente del downgrade.
    # with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('idAlumno'), ['alumno_id'], unique=False)

    # ### end Alembic commands ###
