"""Add is_admin column to alumno table

Revision ID: 08cdb7411ce5
Revises: 
Create Date: 2025-10-01 22:57:18.656032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cdb7411ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=True, default=False)
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
