"""Add es_miembro and fecha_fin_membresia to Alumno

Revision ID: 171c6ad2427f
Revises: 70c404a21237
Create Date: 2025-11-22 22:31:08.142049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171c6ad2427f'
down_revision = '70c404a21237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_miembro', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('fecha_fin_membresia', sa.Date(), nullable=True))

    # El bloque que causaba el error ha sido eliminado.
    # with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idAlumno'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # El bloque correspondiente al drop_index también se elimina aquí para mantener la consistencia.
    # with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('idAlumno'), ['alumno_id'], unique=False)

    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin_membresia')
        batch_op.drop_column('es_miembro')

    # ### end Alembic commands ###
