"""Creacion inicial de tablas

Revision ID: 351e465ba2b0
Revises: c76112c8fb72
Create Date: 2025-11-20 22:49:56.451685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351e465ba2b0'
down_revision = 'c76112c8fb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aplicativo',
    sa.Column('idAplicativo', sa.Integer(), nullable=False),
    sa.Column('idTipoaplicativo', sa.Integer(), nullable=False),
    sa.Column('nombreaplicativo', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=300), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=False),
    sa.Column('urlhelpAplicativo', sa.String(length=500), nullable=True),
    sa.Column('imagen_preview', sa.String(length=500), nullable=True),
    sa.Column('template_file', sa.String(length=120), nullable=True),
    sa.Column('requiere_membresia', sa.Boolean(), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('vistas', sa.Integer(), nullable=False),
    sa.Column('fecharegistro', sa.TIMESTAMP(), nullable=False),
    sa.Column('fechaactualizacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('meta_titulo', sa.String(length=100), nullable=True),
    sa.Column('meta_descripcion', sa.String(length=300), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['idTipoaplicativo'], ['tipo_aplicativo.idtipoaplicativo'], ),
    sa.PrimaryKeyConstraint('idAplicativo')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplicativo')
    # ### end Alembic commands ###
