"""Añadir modelos Modulo y ItemTemario para el temario del curso

Revision ID: 3d2dbd70ac2c
Revises: 0772d5b7e311
Create Date: 2025-11-22 00:23:42.568437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2dbd70ac2c'
down_revision = '0772d5b7e311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.idcurso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_temario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_temario')
    op.drop_table('modulos')
    # ### end Alembic commands ###
