"""Mejora del modelo Grupo con fechas y estado

Revision ID: 562873dd8687
Revises: c4824415995c
Create Date: 2025-10-02 16:06:27.694245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# --- Utilidades seguras para entornos ya divergentes ---
def _column_exists(bind, table_name: str, column_name: str) -> bool:
    query = sa.text(
        """
        SELECT 1
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = :t
          AND COLUMN_NAME = :c
        LIMIT 1
        """
    )
    return bind.execute(query, {"t": table_name, "c": column_name}).fetchone() is not None


def _safe_rename(batch_op, bind, table, old, new, existing_type):
    """Renombra una columna sólo si existe la antigua y no existe la nueva.

    Idempotente: si ya se renombró antes o la fuente no existe, no falla.
    """
    if _column_exists(bind, table, new):  # nueva ya presente
        return
    if _column_exists(bind, table, old):  # renombrar
        batch_op.alter_column(
            old,
            new_column_name=new,
            existing_type=existing_type,
        )
    # else: ninguna existe -> ignorar


def _fk_exists(bind, table_name: str, fk_name: str) -> bool:
        """True si existe una FK con ese nombre."""
        query = sa.text(
                """SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                        WHERE TABLE_SCHEMA = DATABASE()
                            AND TABLE_NAME = :t
                            AND CONSTRAINT_TYPE = 'FOREIGN KEY'
                            AND CONSTRAINT_NAME = :fk
                        LIMIT 1"""
        )
        return bind.execute(query, {"t": table_name, "fk": fk_name}).fetchone() is not None


def _index_exists(bind, table_name: str, index_name: str) -> bool:
        query = sa.text(
                """SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
                        WHERE TABLE_SCHEMA = DATABASE()
                            AND TABLE_NAME = :t
                            AND INDEX_NAME = :i
                        LIMIT 1"""
        )
        return bind.execute(query, {"t": table_name, "i": index_name}).fetchone() is not None

# revision identifiers, used by Alembic.
revision = '562873dd8687'
down_revision = 'c4824415995c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        # Renombres seguros (condicionales)
        _safe_rename(
            batch_op, bind, 'anuncio', 'idAnuncio', 'idanuncio', mysql.INTEGER()
        )
        _safe_rename(
            batch_op, bind, 'anuncio', 'idTipoanuncio', 'idtipoanuncio', mysql.INTEGER()
        )
        _safe_rename(
            batch_op,
            bind,
            'anuncio',
            'rutaarchivoAnuncio',
            'imagen_url',
            mysql.VARCHAR(length=500),
        )

        # Adiciones idempotentes (añadir sólo si no existen)
        nuevas_columnas = [
            ('titulo', sa.String(200), "DEFAULT ''", "''", False),
            ('descripcion', sa.Text(), None, None, True),
            ('enlace', sa.String(500), None, None, True),
            (
                'fechainicio', sa.TIMESTAMP(), 'CURRENT_TIMESTAMP',
                sa.text('CURRENT_TIMESTAMP'), False
            ),
            ('fechafin', sa.TIMESTAMP(), None, None, True),
            ('activo', sa.Boolean(), '1', '1', False),
            ('posicion', sa.Integer(), None, None, True),
            ('impresiones', sa.Integer(), '0', '0', False),
            ('clics', sa.Integer(), '0', '0', False),
            (
                'fecharegistro', sa.TIMESTAMP(), 'CURRENT_TIMESTAMP',
                sa.text('CURRENT_TIMESTAMP'), False
            ),
        ]
        for (
            nombre,
            tipo_col,
            server_default_literal,
            server_default_expr,
            es_nullable,
        ) in nuevas_columnas:
            if not _column_exists(bind, 'anuncio', nombre):
                kwargs = {}
                if server_default_expr is not None:
                    kwargs['server_default'] = server_default_expr
                batch_op.add_column(
                    sa.Column(
                        nombre,
                        tipo_col,
                        nullable=es_nullable,
                        **kwargs,
                    )
                )

    with op.batch_alter_table('aplicativo', schema=None) as batch_op:
        _safe_rename(
            batch_op, bind, 'aplicativo', 'idAplicativo', 'idaplicativo', mysql.INTEGER()
        )
        _safe_rename(
            batch_op,
            bind,
            'aplicativo',
            'idTipoaplicativo',
            'idtipoaplicativo',
            mysql.INTEGER(),
        )
        _safe_rename(
            batch_op,
            bind,
            'aplicativo',
            'nombreaplicativo',
            'nombre',
            mysql.VARCHAR(length=500),
        )
        _safe_rename(
            batch_op,
            bind,
            'aplicativo',
            'slugAplicativo',
            'ruta_archivo',
            mysql.VARCHAR(length=500),
        )
        # Añadir columnas nuevas sólo si faltan
        cols_aplicativo = [
            ('descripcion', sa.Text()),
            ('descripcion_corta', sa.String(300)),
            ('imagen_preview', sa.String(500)),
            ('requiere_membresia', sa.Boolean(), '0'),
            ('premium', sa.Boolean(), '0'),
            ('activo', sa.Boolean(), '1'),
            ('orden', sa.Integer(), '1'),
            ('vistas', sa.Integer(), '0'),
            ('fecharegistro', sa.TIMESTAMP(), 'CURRENT_TIMESTAMP'),
            ('fechaactualizacion', sa.TIMESTAMP(), None),
            ('meta_titulo', sa.String(100)),
            ('meta_descripcion', sa.String(300)),
            ('meta_keywords', sa.String(500)),
        ]
        for nombre, tipo_col, *default in cols_aplicativo:
            if not _column_exists(bind, 'aplicativo', nombre):
                kwargs = {}
                if default and default[0] is not None:
                    val = default[0]
                    if val == 'CURRENT_TIMESTAMP':
                        kwargs['server_default'] = sa.text('CURRENT_TIMESTAMP')
                    else:
                        kwargs['server_default'] = sa.text(f"'{val}'")
                batch_op.add_column(
                    sa.Column(
                        nombre,
                        tipo_col,
                        nullable=True,
                        **kwargs,
                    )
                )
        # FK: sustituir sólo si existía la anterior (no usar try/except porque batch difiere ejecución)
        if _fk_exists(bind, 'aplicativo', 'aplicativo_ibfk_1'):
            batch_op.drop_constraint('aplicativo_ibfk_1', type_='foreignkey')
        # Crear nueva FK sólo si aún no existe
        if not _fk_exists(bind, 'aplicativo', 'fk_aplicativo_idtipoaplicativo_tipo_aplicativo'):
            batch_op.create_foreign_key(
                op.f('fk_aplicativo_idtipoaplicativo_tipo_aplicativo'),
                'tipo_aplicativo',
                ['idtipoaplicativo'],
                ['idtipoaplicativo'],
            )
    # No eliminar la columna original aún (protección de datos)

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.alter_column('duracioncurso',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='int en horas',
               existing_nullable=False)
        batch_op.alter_column('textocortocurso',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('descripcioncurso',
               existing_type=mysql.VARCHAR(length=6000),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('footercurso',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('temariocurso',
               existing_type=mysql.VARCHAR(length=5000),
               type_=sa.Text(),
               comment=None,
               existing_comment='temario en formato json\r\nmodulo->itenm',
               existing_nullable=False)
        batch_op.alter_column('fotocurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment=None,
               existing_comment='Lista de nombres en formato JSON',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='se almacenaran los cursos'
    )

    with op.batch_alter_table('especializacion', schema=None) as batch_op:
        if _index_exists(bind, 'especializacion', 'descEspecializacion'):
            batch_op.drop_index('descEspecializacion')
        batch_op.create_unique_constraint(
            op.f('uq_especializacion_slugEspecializacion'),
            ['slugEspecializacion']
        )

    with op.batch_alter_table('especializacion_curso', schema=None) as batch_op:
        batch_op.alter_column('idEspecializacion',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('idCurso',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        # Añadir nuevas columnas sólo si faltan (no eliminar aún las antiguas)
        for nombre, tipo_col in [
            ('estado', sa.String(length=50)),
            ('fecha_inicio', sa.Date()),
            ('fecha_fin', sa.Date()),
            ('horario', sa.Text()),
            ('capacidad_minima', sa.Integer()),
            ('capacidad_maxima', sa.Integer()),
        ]:
            if not _column_exists(bind, 'grupo', nombre):
                batch_op.add_column(sa.Column(nombre, tipo_col, nullable=True))
        if _fk_exists(bind, 'grupo', 'grupo_ibfk_1'):
            batch_op.drop_constraint('grupo_ibfk_1', type_='foreignkey')
        if _fk_exists(bind, 'grupo', 'grupo_ibfk_2'):
            batch_op.drop_constraint('grupo_ibfk_2', type_='foreignkey')
        # Crear FKs nuevas si no existen ya (nombres generados con op.f pueden variar; comprobamos por nombre deseado)
        if not _fk_exists(bind, 'grupo', 'fk_grupo_idcurso_curso'):
            batch_op.create_foreign_key(
                op.f('fk_grupo_idcurso_curso'), 'curso', ['idcurso'], ['idcurso']
            )
        if not _fk_exists(bind, 'grupo', 'fk_grupo_iddocente_docente'):
            batch_op.create_foreign_key(
                op.f('fk_grupo_iddocente_docente'), 'docente', ['iddocente'], ['iddocente']
            )

    # Migración de datos: ejecutar sólo si las columnas origen existen y las destino están presentes
    if _column_exists(bind, 'grupo', 'fechacurso') and _column_exists(bind, 'grupo', 'horariocurso'):
        op.execute("""
            UPDATE grupo
            SET
                fecha_inicio = COALESCE(CAST(JSON_UNQUOTE(JSON_EXTRACT(fechacurso, '$[0]')) AS DATE), fecha_inicio),
                fecha_fin = COALESCE(CAST(JSON_UNQUOTE(JSON_EXTRACT(fechacurso, '$[1]')) AS DATE), fecha_fin),
                horario = COALESCE(horariocurso, horario),
                estado = COALESCE(estado, CASE
                    WHEN CAST(JSON_UNQUOTE(JSON_EXTRACT(fechacurso, '$[0]')) AS DATE) > CURDATE() THEN 'PROPUESTO'
                    ELSE 'FINALIZADO'
                END),
                capacidad_minima = COALESCE(capacidad_minima, 5),
                capacidad_maxima = COALESCE(capacidad_maxima, 20)
        """)

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        # Endurecer nullability sólo si ya hay datos migrados; envolvemos en try
        try:
            batch_op.alter_column('estado', existing_type=sa.String(length=50), nullable=False)
            batch_op.alter_column('fecha_inicio', existing_type=sa.Date(), nullable=False)
            batch_op.alter_column('capacidad_minima', existing_type=sa.Integer(), nullable=False)
        except Exception:
            pass
        # NO eliminar columnas antiguas para evitar pérdida de datos (se pueden limpiar en una migración posterior controlada)
        # batch_op.drop_column('qsesionesGrupo')
        # batch_op.drop_column('fechacurso')
        # batch_op.drop_column('duraciontotalGrupo')
        # batch_op.drop_column('horariocurso')

    with op.batch_alter_table('sesion', schema=None) as batch_op:
        if _fk_exists(bind, 'sesion', 'sesion_ibfk_1'):
            batch_op.drop_constraint('sesion_ibfk_1', type_='foreignkey')
        if not _fk_exists(bind, 'sesion', 'fk_sesion_idgrupo_grupo'):
            batch_op.create_foreign_key(
                op.f('fk_sesion_idgrupo_grupo'), 'grupo', ['idgrupo'], ['idgrupo']
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('fk_sesion_idgrupo_grupo'), type_='foreignkey')
        batch_op.create_foreign_key('sesion_ibfk_1', 'grupo', ['idgrupo'], ['idgrupo'], onupdate='CASCADE')

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horariocurso', mysql.VARCHAR(length=1000), nullable=False, comment='formato json\r\n-lapso(desde,hasta)\r\n-paises(nombre,emoji)'))
        batch_op.add_column(sa.Column('duraciontotalGrupo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fechacurso', mysql.VARCHAR(length=1000), nullable=False, comment='formato json\r\nfecha'))
        batch_op.add_column(sa.Column('qsesionesGrupo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'se almacenaran los cursos',
        existing_comment=None
    )
        batch_op.drop_constraint(op.f('fk_grupo_iddocente_docente'), type_='foreignkey')
        batch_op.drop_constraint(op.f('fk_grupo_idcurso_curso'), type_='foreignkey')
        batch_op.create_foreign_key('grupo_ibfk_2', 'curso', ['idcurso'], ['idcurso'], onupdate='CASCADE')
        batch_op.create_foreign_key('grupo_ibfk_1', 'docente', ['iddocente'], ['iddocente'], onupdate='CASCADE')
        batch_op.alter_column('visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1:visible\r\n0:oculto',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_column('capacidad_maxima')
        batch_op.drop_column('capacidad_minima')
        batch_op.drop_column('horario')
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('estado')

    with op.batch_alter_table('especializacion_curso', schema=None) as batch_op:
        batch_op.alter_column('idCurso',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('idEspecializacion',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('especializacion', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('uq_especializacion_slugEspecializacion'), type_='unique')
        batch_op.create_index('descEspecializacion', ['descEspecializacion'], unique=True)

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.create_table_comment(
        'se almacenaran los cursos',
        existing_comment=None
    )
        batch_op.alter_column('fotocurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment='Lista de nombres en formato JSON',
               existing_nullable=True)
        batch_op.alter_column('temariocurso',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=5000),
               comment='temario en formato json\r\nmodulo->itenm',
               existing_nullable=False)
        batch_op.alter_column('footercurso',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('descripcioncurso',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=6000),
               existing_nullable=False)
        batch_op.alter_column('textocortocurso',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('duracioncurso',
               existing_type=mysql.INTEGER(),
               comment='int en horas',
               existing_nullable=False)

    with op.batch_alter_table('aplicativo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urlhelpAplicativo', mysql.VARCHAR(length=500), nullable=False))
        batch_op.alter_column('ruta_archivo', new_column_name='slugAplicativo', existing_type=mysql.VARCHAR(length=500))
        batch_op.alter_column('nombre', new_column_name='nombreaplicativo', existing_type=mysql.VARCHAR(length=200))
        batch_op.alter_column('idtipoaplicativo', new_column_name='idTipoaplicativo', existing_type=mysql.INTEGER())
        batch_op.alter_column('idaplicativo', new_column_name='idAplicativo', existing_type=mysql.INTEGER())
        batch_op.drop_constraint(op.f('fk_aplicativo_idtipoaplicativo_tipo_aplicativo'), type_='foreignkey')
        batch_op.create_foreign_key('aplicativo_ibfk_1', 'tipo_aplicativo', ['idTipoaplicativo'], ['idtipoaplicativo'])
        batch_op.drop_column('meta_keywords')
        batch_op.drop_column('meta_descripcion')
        batch_op.drop_column('meta_titulo')
        batch_op.drop_column('fechaactualizacion')
        batch_op.drop_column('fecharegistro')
        batch_op.drop_column('vistas')
        batch_op.drop_column('orden')
        batch_op.drop_column('activo')
        batch_op.drop_column('premium')
        batch_op.drop_column('requiere_membresia')
        batch_op.drop_column('imagen_preview')
        batch_op.drop_column('descripcion_corta')
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.alter_column('idanuncio', new_column_name='idAnuncio', existing_type=mysql.INTEGER())
        batch_op.alter_column('idtipoanuncio', new_column_name='idTipoanuncio', existing_type=mysql.INTEGER())
        # batch_op.alter_column('imagen_url', new_column_name='rutaarchivoAnuncio', existing_type=mysql.VARCHAR(length=500))
        batch_op.drop_constraint(op.f('fk_anuncio_idtipoanuncio_tipo_anuncio'), type_='foreignkey')
        batch_op.drop_column('fecharegistro')
        batch_op.drop_column('clics')
        batch_op.drop_column('impresiones')
        batch_op.drop_column('posicion')
        batch_op.drop_column('activo')
        batch_op.drop_column('fechafin')
        batch_op.drop_column('fechainicio')
        batch_op.drop_column('enlace')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
