"""Eliminar columnas redundantes de membresia en Alumno

Revision ID: 61208478cd1d
Revises: 171c6ad2427f
Create Date: 2025-11-22 23:04:53.915563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61208478cd1d'
down_revision = '171c6ad2427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.drop_column('es_miembro')
        batch_op.drop_column('fecha_fin_membresia')

    with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idAlumno'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idAlumno'), ['alumno_id'], unique=False)

    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_fin_membresia', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('es_miembro', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
