"""Add Horario and PaisHorario models

Revision ID: 70c404a21237
Revises: 3d2dbd70ac2c
Create Date: 2025-11-22 01:35:20.271246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c404a21237'
down_revision = '3d2dbd70ac2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('horainicio', sa.String(length=50), nullable=False),
    sa.Column('horafin', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.idgrupo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paises_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Comentamos o eliminamos esta sección que causa el error.
    # Alembic intentó incorrectamente eliminar un índice necesario.
    # with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('idAlumno'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('idAlumno'), ['alumno_id'], unique=False)

    op.drop_table('paises_horario')
    op.drop_table('horarios')
    # ### end Alembic commands ###
