"""Add marketing, admin, and core models

Revision ID: c4824415995c
Revises: 08cdb7411ce5
Create Date: 2025-10-02 00:43:51.342822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4824415995c'
down_revision = '08cdb7411ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliado_estrategico',
    sa.Column('idaliado', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=False),
    sa.Column('sitio_web', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('impresiones', sa.Integer(), nullable=False),
    sa.Column('clics', sa.Integer(), nullable=False),
    sa.Column('fecha_alianza', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('idaliado')
    )
    op.create_table('configuracion_app',
    sa.Column('idconfiguracion', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('idconfiguracion'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('configuracion_sitio',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('nombre_institucion', sa.String(length=200), nullable=False),
    sa.Column('descripcion_corta', sa.String(length=500), nullable=True),
    sa.Column('descripcion_larga', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('facebook', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('linkedin', sa.String(length=200), nullable=True),
    sa.Column('youtube', sa.String(length=200), nullable=True),
    sa.Column('sitio_activo', sa.Boolean(), nullable=False),
    sa.Column('mensaje_mantenimiento', sa.Text(), nullable=True),
    sa.Column('permitir_registro', sa.Boolean(), nullable=False),
    sa.Column('meta_titulo', sa.String(length=100), nullable=True),
    sa.Column('meta_descripcion', sa.String(length=300), nullable=True),
    sa.Column('meta_keywords', sa.String(length=500), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_config')
    )
    op.create_table('estadistica_sitio',
    sa.Column('id_estadistica', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_estadistica')
    )
    op.create_table('evento_calendario',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_table('notificacion',
    sa.Column('idnotificacion', sa.Integer(), nullable=False),
    sa.Column('tipo_destinatario', sa.String(length=20), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('enlace', sa.String(length=500), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecha_lectura', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('idnotificacion')
    )
    op.create_table('pagina_estatica',
    sa.Column('id_pagina', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('meta_titulo', sa.String(length=100), nullable=True),
    sa.Column('meta_descripcion', sa.String(length=300), nullable=True),
    sa.Column('publicada', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_pagina'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tipo_anuncio',
    sa.Column('idtipoanuncio', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idtipoanuncio')
    )
    op.create_table('tipo_aplicativo',
    sa.Column('idtipoaplicativo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idtipoaplicativo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('actividad_alumno',
    sa.Column('id_actividad', sa.Integer(), nullable=False),
    sa.Column('idAlumno', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['idAlumno'], ['alumno.idAlumno'], ),
    sa.PrimaryKeyConstraint('id_actividad')
    )
    op.create_table('auditoria',
    sa.Column('idauditoria', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('valores_antes', sa.JSON(), nullable=True),
    sa.Column('valores_despues', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('idauditoria')
    )
    op.create_table('intranet_dashboard',
    sa.Column('id_dashboard', sa.Integer(), nullable=False),
    sa.Column('idAlumno', sa.Integer(), nullable=False),
    sa.Column('mostrar_proximos', sa.Boolean(), nullable=False),
    sa.Column('mostrar_calendario', sa.Boolean(), nullable=False),
    sa.Column('mostrar_certificados', sa.Boolean(), nullable=False),
    sa.Column('tema', sa.String(length=20), nullable=True),
    sa.Column('ultima_visita', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['idAlumno'], ['alumno.idAlumno'], ),
    sa.PrimaryKeyConstraint('id_dashboard')
    )
    op.create_table('recordatorio_personal',
    sa.Column('id_recordatorio', sa.Integer(), nullable=False),
    sa.Column('idAlumno', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['idAlumno'], ['alumno.idAlumno'], ),
    sa.PrimaryKeyConstraint('id_recordatorio')
    )
    op.create_table('testimonio_alumno',
    sa.Column('id_testimonio', sa.Integer(), nullable=False),
    sa.Column('idAlumno', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('testimonio', sa.Text(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=False),
    sa.Column('fecha_aprobacion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['idAlumno'], ['alumno.idAlumno'], ),
    sa.PrimaryKeyConstraint('id_testimonio')
    )
    op.create_table('alumno_grupo',
    sa.Column('idAlumno_grupo', sa.Integer(), nullable=False),
    sa.Column('idAlumno', sa.Integer(), nullable=False),
    sa.Column('idGrupo', sa.Integer(), nullable=False),
    sa.Column('fecharegistro', sa.TIMESTAMP(), nullable=False),
    sa.Column('preciodecompra', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('transaccion', sa.String(length=300), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('certificado', sa.String(length=200), nullable=True),
    sa.Column('uniq_registro', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['idAlumno'], ['alumno.idAlumno'], ),
    sa.ForeignKeyConstraint(['idGrupo'], ['grupo.idgrupo'], ),
    sa.PrimaryKeyConstraint('idAlumno_grupo')
    )
    op.create_table('grupo_sesion',
    sa.Column('idgruposesion', sa.Integer(), nullable=False),
    sa.Column('idgrupo', sa.Integer(), nullable=False),
    sa.Column('idsesion', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('grabacion', sa.String(length=500), nullable=True),
    sa.Column('materiales', sa.String(length=500), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idgrupo'], ['grupo.idgrupo'], ),
    sa.ForeignKeyConstraint(['idsesion'], ['sesion.idsesion'], ),
    sa.PrimaryKeyConstraint('idgruposesion')
    )
    
    # Primero eliminar las foreign keys antes de eliminar las tablas
    with op.batch_alter_table('aplicativo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('aplicativo_ibfk_1'), type_='foreignkey')
    
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.alter_column('duracioncurso',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='int en horas',
               existing_nullable=False)
        batch_op.alter_column('descripcioncurso',
               existing_type=mysql.TEXT(),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('footercurso',
               existing_type=mysql.TEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('temariocurso',
               existing_type=mysql.TEXT(),
               type_=mysql.TEXT(),
               comment=None,
               existing_comment='temario en formato json\r\nmodulo->itenm',
               existing_nullable=False)
        batch_op.alter_column('fotocurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment=None,
               existing_comment='Lista de nombres en formato JSON',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='se almacenaran los cursos'
    )

    with op.batch_alter_table('especializacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('descEspecializacion'))
        batch_op.create_unique_constraint(None, ['slugEspecializacion'])

    with op.batch_alter_table('especializacion_curso', schema=None) as batch_op:
        batch_op.alter_column('idEspecializacion',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('idCurso',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.alter_column('horariocurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment=None,
               existing_comment='formato json\r\n-lapso(desde,hasta)\r\n-paises(nombre,emoji)',
               existing_nullable=False)
        batch_op.alter_column('fechacurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment=None,
               existing_comment='formato json\r\nfecha',
               existing_nullable=False)
        batch_op.alter_column('visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='1:visible\r\n0:oculto',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.drop_constraint(batch_op.f('grupo_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('grupo_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'docente', ['iddocente'], ['iddocente'])
        batch_op.create_foreign_key(None, 'curso', ['idcurso'], ['idcurso'])
        batch_op.drop_table_comment(
            existing_comment='se almacenaran los cursos'
        )
        # --- INICIO DE LA MIGRACIÓN DE DATOS MANUAL ---
        op.execute("""
            UPDATE grupo
            SET
                -- Extraer la primera fecha del JSON y asignarla a fecha_inicio
                fecha_inicio = CAST(JSON_UNQUOTE(JSON_EXTRACT(fechacurso, '$[0]')) AS DATE),
                -- Extraer la segunda fecha del JSON y asignarla a fecha_fin
                fecha_fin = CAST(JSON_UNQUOTE(JSON_EXTRACT(fechacurso, '$[1]')) AS DATE),
                -- Mover el contenido de horariocurso a horario_descripcion
                horario = horariocurso,
                -- Establecer un estado por defecto basado en la fecha de inicio
                estado = CASE
                    WHEN CAST(JSON_UNQUOTE(JSON_EXTRACT(fechacurso, '$[0]')) AS DATE) > CURDATE() THEN 'PROPUESTO'
                    ELSE 'FINALIZADO'
                END;
        """)
        # --- FIN DE LA MIGRACIÓN DE DATOS MANUAL ---
        batch_op.drop_column('horariocurso')
        batch_op.drop_column('fechacurso')
        batch_op.drop_column('qsesionesGrupo')
        batch_op.drop_column('duraciontotalGrupo')

    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sesion_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'grupo', ['idgrupo'], ['idgrupo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sesion_ibfk_1'), 'grupo', ['idgrupo'], ['idgrupo'], onupdate='CASCADE')

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.create_table_comment(
        'se almacenaran los cursos',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('grupo_ibfk_2'), 'curso', ['idcurso'], ['idcurso'], onupdate='CASCADE')
        batch_op.create_foreign_key(batch_op.f('grupo_ibfk_1'), 'docente', ['iddocente'], ['iddocente'], onupdate='CASCADE')
        batch_op.alter_column('visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment='1:visible\r\n0:oculto',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('fechacurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment='formato json\r\nfecha',
               existing_nullable=False)
        batch_op.alter_column('horariocurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment='formato json\r\n-lapso(desde,hasta)\r\n-paises(nombre,emoji)',
               existing_nullable=False)

    with op.batch_alter_table('especializacion_curso', schema=None) as batch_op:
        batch_op.alter_column('idCurso',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('idEspecializacion',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('especializacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('descEspecializacion'), ['descEspecializacion'], unique=True)

    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.create_table_comment(
        'se almacenaran los cursos',
        existing_comment=None
    )
        batch_op.alter_column('fotocurso',
               existing_type=mysql.VARCHAR(length=1000),
               comment='Lista de nombres en formato JSON',
               existing_nullable=True)
        batch_op.alter_column('temariocurso',
               existing_type=mysql.TEXT(),
               type_=mysql.VARCHAR(length=5000),
               comment='temario en formato json\r\nmodulo->itenm',
               existing_nullable=False)
        batch_op.alter_column('footercurso',
               existing_type=mysql.TEXT(),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('descripcioncurso',
               existing_type=mysql.TEXT(),
               type_=mysql.VARCHAR(length=6000),
               existing_nullable=False)
        batch_op.alter_column('duracioncurso',
               existing_type=mysql.INTEGER(),
               comment='int en horas',
               existing_nullable=False)

    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('resetPassword',
               existing_type=mysql.VARCHAR(length=100),
               comment='hash md5 para ubicar un reseteo de contraseña',
               existing_nullable=True)
        batch_op.alter_column('imagenAlumno',
               existing_type=mysql.VARCHAR(length=500),
               comment='el nombre de la imagen en la carpeta fotos',
               existing_nullable=True)

    op.drop_table('grupo_sesion')
    op.drop_table('alumno_grupo')
    op.drop_table('testimonio_alumno')
    op.drop_table('recordatorio_personal')
    op.drop_table('intranet_dashboard')
    op.drop_table('auditoria')
    op.drop_table('actividad_alumno')
    op.drop_table('user')
    op.drop_table('tipo_aplicativo')
    op.drop_table('tipo_anuncio')
    op.drop_table('pagina_estatica')
    op.drop_table('notificacion')
    op.drop_table('evento_calendario')
    op.drop_table('estadistica_sitio')
    op.drop_table('configuracion_sitio')
    op.drop_table('configuracion_app')
    op.drop_table('aliado_estrategico')
    # ### end Alembic commands ###
