"""Sincronización de modelos post-refactorización

Revision ID: e9b2a1a2bca3
Revises: 20251003_cleanup_legacy
Create Date: 2025-11-16 22:43:56.088899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9b2a1a2bca3'
down_revision = '20251003_cleanup_legacy'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: Se ha modificado manualmente para usar alter_column y evitar pérdida de datos.
    with op.batch_alter_table('alumno_grupo', schema=None) as batch_op:
        # Renombrar 'id' a 'idAlumnoGrupo' para que coincida con el modelo
        batch_op.alter_column('id', new_column_name='idAlumnoGrupo', existing_type=mysql.INTEGER(), autoincrement=True, nullable=False)
        batch_op.alter_column('fecha_inscripcion',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        # Limpiar registros huérfanos ANTES de crear la foreign key.
        op.execute(
            "DELETE FROM anuncio WHERE idtipoanuncio NOT IN (SELECT idtipoanuncio FROM tipo_anuncio)"
        )
        batch_op.create_foreign_key('fk_anuncio_tipo_anuncio_idtipoanuncio', 'tipo_anuncio', ['idtipoanuncio'], ['idtipoanuncio'])

    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.alter_column('capacidad_minima',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grupo', schema=None) as batch_op:
        batch_op.alter_column('capacidad_minima',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('anuncio', schema=None) as batch_op:
        batch_op.drop_constraint('fk_anuncio_tipo_anuncio_idtipoanuncio', type_='foreignkey')

    with op.batch_alter_table('alumno_membresia', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicio',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('alumno_grupo', schema=None) as batch_op:
        batch_op.alter_column('fecha_inscripcion',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('idAlumnoGrupo', new_column_name='id', existing_type=mysql.INTEGER(), autoincrement=True, nullable=False)

    # ### end Alembic commands ###
