"""Aumentar longitud de hash de contraseña para Alumno

Revision ID: f369a4d2a891
Revises: e9b2a1a2bca3
Create Date: 2025-11-16 23:54:44.170603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f369a4d2a891'
down_revision = 'e9b2a1a2bca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: Se ha modificado manualmente para realizar únicamente el cambio necesario.
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.alter_column('claveAlumno', existing_type=mysql.VARCHAR(length=100), type_=sa.String(length=256), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.alter_column('claveAlumno', existing_type=sa.String(length=256), type_=mysql.VARCHAR(length=100), existing_nullable=False)

    # ### end Alembic commands ###
